version: '2.1'
services:
  live-reload:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - live-reload
    volumes:
      - .:/semana_js_expert_6
      - node_modules:/semana_js_expert_6/node_modules
    ports:
      - 3000:3000

  test:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test
    volumes:
      - .:/semana_js_expert_6
      - node_modules:/semana_js_expert_6/node_modules

  test-watch:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test:watch
    volumes:
      - .:/semana_js_expert_6
      - node_modules:/semana_js_expert_6/node_modules

  test-coverage:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test:coverage
    volumes:
      - .:/semana_js_expert_6
      - node_modules:/semana_js_expert_6/node_modules

volumes:
  node_modules: {}
